### ISSUE TITLE
8bitdo Controller not working

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#223]
I noticed my 8 bitdo controllers are not working when I plug them in, however I do get the message HUD that it detected the controller being plugged in. My playstation 4 controller seems to work just fine. Im using the raspberry pi images.

**Comment by kivutar** [comment]
What 8bitdo controller are you using exactly? For now the only one with an autoconfig is this one https://github.com/libretro/ludo/blob/master/input/binds_linux.go#L12

**Comment by kivutar** [comment]
Please try to update to v1.0-alpha19

**Comment by johnnyq** [comment]
I installed the latest 1.0 alpha 19 and when i plug in the controller it says it detects it as the snes30 but the buttons do not work

**Comment by kivutar** [comment]
OK :(

**Comment by johnnyq** [comment]
@kivutar Is there anything else I can help test or try to help with this issue?

**Comment by kivutar** [comment]
No, I'm back home and I have the 8bitdo controller with me. I have everything I need to check the cause of the bug. I only need to have free time. If somebody else have some spare time and know how to debug inputs, please jump in.

**Comment by johnnyq** [comment]
I wish i knew more about this that I could help. Im okay with reporting bugs but wish I could do more Thank you for your time and dedication.

**Comment by kivutar** [comment]
The solution is certainly to change something on the LudOS side, as the controller is working normally on other linuces.

**Comment by kivutar** [comment]
Solved now

**Comment by johnnyq** [comment]
Hi @kivutar I seen the issue got closed but I still cannot use my 4 8bitdo controllers. This was texted with 0.9.2 on Mint 19.2 Kernel 5.0 and LudOS Alpha 25 on Raspberry pi3b+

The Model Numbers are SNES30, SFC30, SF30 and SN30 Pro

I attached Screen shots of 2 of the controllers

![2019-10-23 14-38-27-1](https://user-images.githubusercontent.com/1812594/67424256-54b4ac80-f5c5-11e9-8ada-7ab3084cb06b.JPG)
![2019-10-23 14-38-37-1](https://user-images.githubusercontent.com/1812594/67424257-54b4ac80-f5c5-11e9-8bb4-2928e9acf3c2.JPG)
![2019-10-23 14-38-48-1](https://user-images.githubusercontent.com/1812594/67424258-54b4ac80-f5c5-11e9-9add-4012e6f8bf7a.JPG)
![2019-10-23 14-38-56-1](https://user-images.githubusercontent.com/1812594/67424259-554d4300-f5c5-11e9-85c7-35b5d95c59ff.JPG)

**Comment by johnnyq** [comment]
Also I tried some other controllers as well. I got a playstation classic and sega classic. The controllers detect just fine, but none of the buttons work.

**Comment by johnnyq** [comment]
I tried the Nintendo switch pro controller as well for the fun of it and it detects but none of the buttons appear to be mapped

**Comment by johnnyq** [comment]
I see the file you recently updated called go binds it looks like it has the following controllers with mappings

"Xbox Controller":            xboxOneJoyBinds,
	"Wireless Controller":        ds4JoyBinds,
	"PLAYSTATION(R)3 Controller": ds3JoyBinds,
	"8Bitdo NES30 Pro":           nes30proJoyBinds,
is it just a matter of adding other controllers to this file and recompiling, im not sure though
