### ISSUE TITLE
ds4windows guide button

### ISSUE THREAD

**Issue by schrock** [libretro/ludo#343]
OS: Windows 10

Controller: DS4 emulating an Xbox 360 controller via [DS4Windows](https://github.com/Ryochan7/DS4Windows)

Based on the button indicators on the bottom of the screen, I am guessing that the Xbox guide button is meant to open/close the menu UI when playing a game, but it does not currently function.

**Comment by kivutar** [comment]
Windows has his own way to treat the guide button, since there is the xbox app on Windows.
I'm not sure if there is a way to access it. Maybe try the comments here https://www.reddit.com/r/pcgaming/comments/3udzes/for_anyone_whos_xbox_one_controller_guide_button/

**Comment by kivutar** [comment]
I've pushed a fix that makes the guide button work. It will land in the next release.

It was broken by a Windows upgrade or by an upgrade to the DS4 firmware.

I don't remember if I was usinng DS4Windows for my driver however.

**Comment by schrock** [comment]
The guide button still doesn't work in v0.12.0, but the L3+R3 menu toggle is sufficient for the purpose of opening the menu via the controller.

**Comment by kivutar** [comment]
I tried again yesterday and the guide button works for me.

I think it's due to the fact that you emulate a Xbox pad.

In this case this bug becomes a duplicate of https://github.com/libretro/ludo/issues/445
